### ISSUE TITLE
path issues in chromium extension context?

### ISSUE THREAD

**Issue by du5t** [dominictarr/sodium-browserify#3]
> Cannot find module './bindings'(anonymous function) @ capsule-bundle.js:39828

```
{"sodium-browserify/browser":428}],200:[function(require,module,exports){
(function (process){

if(process.env.CHLORIDE_JS)
  return module.exports = require('./browser')

try {
  var r = require //fool browserify
  module.exports = r('./bindings')
} catch (err) {
  console.error(err.message)
  module.exports = require('./browser')
}
```

you may have fooled browserify, but you don't fool me!

actually i'm stumped. see https://github.com/du5t/capsule to reproduce.

**Comment by dominictarr** [comment]
This is where chloride loads the compiled sodium binary, or if it can't, falls back to the javascript version.
But this is the output of browserify, right? so it has to use the javascript version. I guess the problem here is we should have a better error message.

**Comment by dominictarr** [comment]
oops, I had already fixed this, but just hadn't npm published, upgrade to latest:
https://github.com/dominictarr/chloride/blob/master/index.js#L9-L10

**Comment by du5t** [comment]
closing since we went with another mechanism for capsule and kept sodium out of the addon.
