### ISSUE TITLE
Wasm never loaded

### ISSUE THREAD

**Issue by arj03** [dominictarr/sodium-browserify#5]
I'm trying to test the performance of wasm compared to libsodium c version. I noticed that the js fallback is really slow and that the wasm version did not seem to load.

I traced down the problem to being that libsodium.ready is never called. And it appears to be timing related. Meaning that if you call tweetnacl functions before wasm has finished loading, then wasm doesn't seem to load, but if you wait a little it works :(

The way I reproduced this was by running either [00-generate](https://github.com/ssbc/bench-ssb/blob/master/00-generate.js) or 01-validate from bench-ssb. And adding a setTimeout 200ms on this [line](https://github.com/ssbc/bench-ssb/blob/master/00-generate.js#L8) makes it load wasm.

**Comment by arj03** [comment]
Right, the readme actually mentions this, but there is no way to know if its ready or not. Hmm

**Comment by dominictarr** [comment]
if all the crypto you do is sync without io, then your code likely never waits long enough for it to load.
maybe whats needed is logging if any crypto method is used before wasm is loaded?

**Comment by arj03** [comment]
I'm thinking something like an event similar to multiserver:listening we have in ssb?

**Comment by dominictarr** [comment]
uh, but then sodium-browserify would need an event emitter... I'd rather not add that, we don't need this to be extensible

**Comment by arj03** [comment]
Can you think of a better way to do it so there was a way to know when wasm is ready?

**Comment by arj03** [comment]
Maybe that didn't come across right. Sorry. What I meant was that I will be happy to implement some sort of workaround for this. Just need to know what it could be, first :)

**Comment by dominictarr** [comment]
I would probably do it like:

``` js
function wrapWarn(name, fn) {
  module.exports[name] = function () {
   var args = [].slice.call(arguments)
    console.log('method '+name+' called before wasm loaded')
   module.exports[name] = fn //so that it only logs once, and also next time skips [].slice
    return fn.apply(null, args)
  }
}
```

and after wasm is loaded it will replace all of those too. hmm, funny feeling there might be something like this already?

**Comment by arj03** [comment]
Hmm. I really don't understand why you don't want an event emitter. I've changed the PR in  #6 to show that it's a really small change. This allows me to run bench-ssb properly on my phone.

On my machine 200ms is not *always* enough, so the library behaves very randomly, I have a feeling it might also be the case on phones.
